# Site settings
title: Curious Intellect 
header-img: img/home-bg.png
email: boumizaalya@gmail.com
copyright_name: Alya12
description: > # this means to ignore newlines until "baseurl:"
  A little Bit of Everything 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Alya12
learn_profile: Alya12
email_username: boumizaalya@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
